export const alphaArray =[
    {alpha:"a", disabled:false},
    {alpha:"b", disabled:false},
    {alpha:"c", disabled:false},
    {alpha:"d", disabled:false},
    {alpha:"e", disabled:false},
    {alpha:"f", disabled:false},
    {alpha:"g", disabled:false},
    {alpha:"h", disabled:false},
    {alpha:"i", disabled:false},
    {alpha:"j", disabled:false},
    {alpha:"k", disabled:false},
    {alpha:"l", disabled:false},
    {alpha:"m", disabled:false},
    {alpha:"n", disabled:false},
    {alpha:"o", disabled:false},
    {alpha:"p", disabled:false},
    {alpha:"q", disabled:false},
    {alpha:"r", disabled:false},
    {alpha:"s", disabled:false},
    {alpha:"t", disabled:false},
    {alpha:"u", disabled:false},
    {alpha:"v", disabled:false},
    {alpha:"w", disabled:false},
    {alpha:"x", disabled:false},
    {alpha:"y", disabled:false},
    {alpha:"z", disabled:false},
]